#!/bin/bash
# Tests for the rolling history store and the analytics computed from it.
#
# The store records DELTAS, not cumulative counters, so an engine restart or a
# traffic reset simply yields a smaller bucket instead of poisoning every
# window that spans it. These tests use hand-written fixtures rather than
# fixtures generated by the code under test, so the expected values are
# checkable by eye.
set -o pipefail

if [ "${BASH_VERSINFO[0]:-0}" -lt 4 ]; then
    echo "SKIP: bash 4+ required (got ${BASH_VERSION:-unknown})" >&2
    exit 0
fi

TEST_TMPDIR=$(mktemp -d)
INSTALL_DIR="$TEST_TMPDIR/install"
mkdir -p "$INSTALL_DIR/relay_stats/history"
OFFSET_FILE="$INSTALL_DIR/relay_stats/tg_offset"

# busybox ships a flock applet that accepts -n but NOT -w. Putting one on PATH reproduces
# Alpine's behaviour here, so the history-prune regression is caught on every platform
# rather than only on busybox hosts.
FAKEBIN="$TEST_TMPDIR/bin"
mkdir -p "$FAKEBIN"
cat >"$FAKEBIN/flock" <<'FLOCK_EOF'
#!/bin/bash
for _a in "$@"; do
    case "$_a" in
    -w*) echo "flock: unrecognized option: w" >&2; exit 1 ;;
    esac
done
exit 0
FLOCK_EOF
chmod +x "$FAKEBIN/flock"
PATH="$FAKEBIN:$PATH"
export PATH

MTPROXYMAX_SOURCE_ONLY=true source "$(dirname "${BASH_SOURCE[0]}")/../mtproxymax.sh"
set +e
trap 'rm -rf "$TEST_TMPDIR"' EXIT

TESTS_RUN=0
TESTS_FAILED=0
assert_eq() {
    local name="$1" want="$2" got="$3"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [ "$got" = "$want" ]; then printf '  PASS  %s\n' "$name"
    else TESTS_FAILED=$((TESTS_FAILED + 1)); printf '  FAIL  %s\n         got=%q\n        want=%q\n' "$name" "$got" "$want"; fi
}
assert_ok() {
    local name="$1" cond="$2"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [ "$cond" -eq 0 ] 2>/dev/null; then printf '  PASS  %s\n' "$name"
    else TESTS_FAILED=$((TESTS_FAILED + 1)); printf '  FAIL  %s\n' "$name"; fi
}

telegram_generate_service_script
DAEMON="$INSTALL_DIR/mtproxymax-telegram.sh"
FNS="$TEST_TMPDIR/history.sh"
awk '/^# >>> TG_HISTORY_BEGIN$/,/^# <<< TG_HISTORY_END$/' "$DAEMON" > "$FNS"
assert_eq "history block found in the daemon" 1 \
    "$(grep -c '^# >>> TG_HISTORY_BEGIN$' "$FNS")"
assert_eq "history extraction is valid bash" 0 \
    "$(bash -n "$FNS" 2>/dev/null; echo $?)"
source "$FNS"

HIST="$INSTALL_DIR/relay_stats/history"
NOW=1000000

echo "Telegram history store tests"

# ── Summary: window sums, period-over-period, peak and average ───────────────
# window = 1000s, so cur covers epoch >= 999000 and prev covers 998000..998999.
#   prev in = 200+200 = 400, prev out = 300+300 = 600, prev total = 1000
#   cur  in = 400+600 = 1000, cur out = 600+400 = 1000, cur total = 2000
#   pct = (2000-1000)*100/1000 = +100
#   intervals: 998500->998800 gap 300 delta 500  = 1.67 B/s
#              998800->999500 gap 700 delta 1000 = 1.43 B/s
#              999500->999800 gap 300 delta 1000 = 3.33 B/s   <- peak
#   span = 999800-999500 = 300 (cur window), total 2000 -> avg 6
cat > "$HIST/global.tsv" <<'EOF'
998500|200|300|5|-
998800|200|300|6|-
999500|400|600|7|-
999800|600|400|8|-
EOF
: > "$HIST/users.tsv"

assert_eq "summary reports the current and previous windows" \
    "1000|1000|400|600|100|3|6|2|300" "$(history_summary 1000 "$NOW")"

# A window with nothing in the previous period reports "n/a" — never inf/nan,
# and never a numeric sentinel that a real -1% would collide with.
cat > "$HIST/global.tsv" <<'EOF'
999500|400|600|7|-
999800|600|400|8|-
EOF
_sum=$(history_summary 1000 "$NOW")
assert_eq "period-over-period is n/a when there is no previous window" \
    "n/a" "$(printf '%s' "$_sum" | cut -d'|' -f5)"
assert_ok "no inf or nan leaks into the summary" \
    "$(printf '%s' "$_sum" | grep -qE 'inf|nan' && echo 1 || echo 0)"

# A genuine decrease is still numeric, and distinguishable from n/a.
# prev total 1250, cur total 1000 -> -20%
cat > "$HIST/global.tsv" <<'EOF'
998500|600|650|5|-
999500|400|600|7|-
999800|0|0|0|-
EOF
assert_eq "a real decrease is reported numerically" \
    "-20" "$(history_summary 1000 "$NOW" | cut -d'|' -f5)"

# An empty store must not crash or emit garbage.
: > "$HIST/global.tsv"
assert_eq "an empty store yields a zeroed summary" \
    "0|0|0|0|n/a|0|0|0|0" "$(history_summary 1000 "$NOW")"

# ── Peak must use the REAL inter-sample gap, not the nominal interval ────────
# 1000 bytes over a 100s gap is 10 B/s. Assuming a nominal 300s bucket would
# report 3 B/s, so this pins the honest calculation.
cat > "$HIST/global.tsv" <<'EOF'
999000|0|0|0|-
999100|1000|0|0|-
999800|1000|0|0|-
EOF
assert_eq "peak uses the actual gap between samples" \
    "10" "$(history_summary 1000 "$NOW" | cut -d'|' -f6)"

# ── An engine-restart marker must not be summed as traffic ───────────────────
cat > "$HIST/global.tsv" <<'EOF'
999500|400|600|7|-
999600|0|0|0|R
999800|600|400|8|-
EOF
assert_eq "restart rows still contribute their delta" \
    "1000" "$(history_summary 1000 "$NOW" | cut -d'|' -f1)"

# ── Per-user windows, in one pass, including users with no history ───────────
cat > "$HIST/users.tsv" <<'EOF'
998800|alice|100|100
999500|alice|300|200
999800|bob|50|50
999800|alice|100|100
EOF
_u=$(history_users 1000 "$NOW" alice bob carol)
assert_eq "per-user window sums are exact" \
    "alice|400|300
bob|50|50
carol|0|0" "$_u"

# Requesting no labels must not hang or error.
assert_eq "an empty label list yields nothing" "" "$(history_users 1000 "$NOW")"

# ── Hourly buckets ───────────────────────────────────────────────────────────
cat > "$HIST/global.tsv" <<'EOF'
999500|400|600|7|-
999800|600|400|8|-
EOF
_h=$(history_hourly 1000 "$NOW")
assert_eq "hourly series has 24 buckets" 24 "$(printf '%s\n' "$_h" | tr ' ' '\n' | grep -c .)"
assert_eq "hourly buckets sum to the window total" 2000 \
    "$(printf '%s\n' "$_h" | tr ' ' '\n' | awk '{s+=$1} END{printf "%.0f", s+0}')"

# ── Top talkers ──────────────────────────────────────────────────────────────
cat > "$HIST/users.tsv" <<'EOF'
999500|alice|100|100
999500|bob|500|500
999500|carol|300|300
EOF
assert_eq "top talkers are ordered by volume" \
    "bob|1000
carol|600
alice|200" "$(history_top 1000 "$NOW" 3)"
assert_eq "top talkers honours the limit" 1 "$(history_top 1000 "$NOW" 1 | wc -l | tr -d ' ')"

# ── Appending a sample ───────────────────────────────────────────────────────
rm -f "$HIST/global.tsv" "$HIST/users.tsv"
_bucket_in=111; _bucket_out=222; _bucket_marker="-"; _bucket_conns=0
# carol is wholly idle in both directions so she must produce no row at all.
declare -A _bucket_user_in=([alice]=10 [carol]=0)
declare -A _bucket_user_out=([alice]=30 [carol]=0)
history_sample 5000
history_sample 5300
assert_eq "each sample appends one global row" 2 "$(wc -l < "$HIST/global.tsv" | tr -d ' ')"
assert_eq "global rows carry five pipe-separated fields" \
    "5" "$(awk -F'|' 'NR==1{print NF}' "$HIST/global.tsv")"
assert_eq "the global row holds the bucket totals" "5000|111|222|0|-" "$(head -1 "$HIST/global.tsv")"

# A user with a zero delta is omitted: a mostly-idle fleet must not write a row
# per user per sample.
# The first sample consumes the bucket, so the second writes no user row.
assert_eq "active users are written once per sample" 1 "$(grep -c 'alice' "$HIST/users.tsv")"
assert_ok "a zero-delta user gets no row" \
    "$(grep -q '^5000|carol|' "$HIST/users.tsv" && echo 1 || echo 0)"

# The buckets must be zeroed after a sample, or the next one double-counts.
assert_eq "sampling resets the global bucket" "0:0" "${_bucket_in}:${_bucket_out}"
assert_eq "sampling resets the per-user bucket" "0:0" "${_bucket_user_in[alice]:-0}:${_bucket_user_out[alice]:-0}"

# ── The record format's field count is a contract ────────────────────────────
assert_eq "user rows carry four pipe-separated fields" \
    "4" "$(awk -F'|' 'NR==1{print NF}' "$HIST/users.tsv")"

# ── Concurrent appends ───────────────────────────────────────────────────────
# The daemon is the only appender, so these need no lock — but O_APPEND must
# still not interleave rows.
rm -f "$HIST/global.tsv"
for _i in $(seq 1 20); do
    ( _bucket_in=$_i; _bucket_out=$_i; _bucket_marker="-"; history_sample "$(( 6000 + _i ))" ) &
done
wait
assert_eq "20 concurrent appends produce 20 well-formed rows" 20 \
    "$(awk -F'|' 'NF==5' "$HIST/global.tsv" | wc -l | tr -d ' ')"
assert_eq "concurrent appends produce no extra rows" 20 \
    "$(wc -l < "$HIST/global.tsv" | tr -d ' ')"

# ── Pruning ──────────────────────────────────────────────────────────────────
rm -f "$HIST/global.tsv" "$HIST/users.tsv"
for _d in $(seq 0 9); do
    printf '%s|10|10|1|-\n' "$(( NOW - _d * 86400 ))" >> "$HIST/global.tsv"
    printf '%s|alice|10|10\n' "$(( NOW - _d * 86400 ))" >> "$HIST/users.tsv"
done
history_prune 7 "$NOW"
assert_ok "pruning keeps samples inside the retention window" \
    "$([ "$(wc -l < "$HIST/global.tsv" | tr -d ' ')" -ge 7 ] && echo 0 || echo 1)"
assert_ok "pruning drops samples older than the window" \
    "$(awk -F'|' -v c=$(( NOW - 7 * 86400 )) '$1 < c' "$HIST/global.tsv" | grep -q . && echo 1 || echo 0)"
assert_eq "pruning leaves no blank lines" 0 \
    "$(grep -c '^$' "$HIST/global.tsv")"
assert_ok "pruning keeps every surviving row well-formed" \
    "$(awk -F'|' 'NF!=5' "$HIST/global.tsv" | grep -q . && echo 1 || echo 0)"

# Pruning twice must change nothing.
_before=$(cat "$HIST/global.tsv")
history_prune 7 "$NOW"
assert_eq "pruning is idempotent" "$_before" "$(cat "$HIST/global.tsv")"

# 10 daily samples with 7-day retention leaves day 0 through day 7 inclusive.
assert_eq "pruning keeps exactly the retained days" 8 \
    "$(wc -l < "$HIST/global.tsv" | tr -d ' ')"
assert_eq "per-user rows are pruned on the same boundary" 8 \
    "$(wc -l < "$HIST/users.tsv" | tr -d ' ')"

# ── Sparkline ────────────────────────────────────────────────────────────────
assert_eq "sparkline of an idle series is all floor" "▁▁▁" "$(_tg_spark "0 0 0")"
assert_eq "sparkline scales to its own peak" "▃▅█" "$(_tg_spark "1 2 3")"
assert_eq "sparkline of nothing is empty" "" "$(_tg_spark "")"
# Each bar glyph is 3 UTF-8 bytes, and this host runs a C locale where wc -m
# counts bytes — so byte length is the locale-independent way to count glyphs.
# It is also the regression guard for the multibyte hazard: a byte-wise split
# of the glyph table would yield a wrong byte count here.
assert_eq "sparkline emits one glyph per bucket" 9 \
    "$(printf '%s' "$(_tg_spark "1 2 3")" | wc -c | tr -d ' ')"
assert_eq "sparkline length matches the series" 72 \
    "$(_tg_spark "$(history_hourly 1000 "$NOW")" | wc -c | tr -d ' ')"

# ── Percentage formatting ────────────────────────────────────────────────────
assert_eq "an increase is shown with an up arrow" "  ▲12%" "$(_tg_pct_str 12)"
assert_eq "a decrease is shown with a down arrow" "  ▼7%" "$(_tg_pct_str -7)"
assert_eq "no change is shown as flat" "  ▬0%" "$(_tg_pct_str 0)"
assert_eq "n/a prints nothing at all" "" "$(_tg_pct_str "n/a")"
assert_eq "garbage prints nothing at all" "" "$(_tg_pct_str "")"

printf '\n%d tests, %d failures\n' "$TESTS_RUN" "$TESTS_FAILED"
[ "$TESTS_FAILED" -eq 0 ]
